name: Featured star list languages
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update Featured star list languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: metrics.plugin.starlists.languages.svg
          user: AlexLog94
          base: "repositories"
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 50
          plugin_starlists_limit_repositories: 50
          plugin_starlists_only: TC39
  
  delete-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 2
          keep_minimum_runs: 2

