name: Stats
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Featured star list languages
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.starlists.languages.svg
        token: NOT_NEEDED
        user: AlexLog94
        base: ""
        plugin_starlists: yes
        plugin_starlists_languages: yes
        plugin_starlists_only: TC39


    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        retain_days: 2
        keep_minimum_runs: 2


