name: Achievements
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Featured star list languages
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.starlists.languages.svg
        token: ${{ secrets.GH_TOKEN }}
        user: AlexLog94
        base: ""
        plugin_starlists: yes
        plugin_starlists_languages: yes
        plugin_starlists_limit_languages: 8
        plugin_starlists_limit_repositories: 0
        plugin_starlists_only: Awesome


  delete-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 2
          keep_minimum_runs: 2

